### ISSUE TITLE
Jetson Nano- demo page not fully loaded in Firefox

### ISSUE THREAD

**Issue by paulirotta** [tomaszpolanski/flutter-animations#7]
Hi T! Sending you a juicy virtual steak...

The online test page you have work in Chromium but not Firefox. No scrolling, no animation, only the first demo display before something bombs. Flutter beta pains?

Firefox and Chromium on Nano (ARM) display flutter web graphs just fine on the Nano. I did not test extensively other Flutter parts on this platform. Results on Raspberry Pi are likely similar.

**Comment by tomaszpolanski** [comment]
Hey Paul!
Yep, the web stuff is still an early preview so there are things that won't work. Still, I will check out what's up with FF, I might be messing something up

**Comment by paulirotta** [comment]
I did some poking around and updated to Firefox beta channel on the Nano.
It seems to be non-deterministic. Reloading gives about 4-in-5 chance of deadlock or whatever is happening on this medium-slow machine. Changing various privacy blockers in the browser had not effect. So yeah, seems to be just Flutter growing pains.
Thanks for the demos- keep on leading!
